pages = [{"l":"index.html#","e":false,"i":"","n":"Iris","t":"Iris","d":"","k":"static","x":""},
{"l":"com/alecdorrington/iris.html#","e":false,"i":"","n":"com.alecdorrington.iris","t":"com.alecdorrington.iris","d":"","k":"package","x":""},
{"l":"com/alecdorrington/iris/Chat.html#","e":false,"i":"","n":"Chat","t":"Chat(messages: List[Message] = ..., system: Option[String] = ...)","d":"com.alecdorrington.iris","k":"class","x":""},
{"l":"com/alecdorrington/iris/Chat.html#add-2ff","e":false,"i":"","n":"add","t":"add(message: Message): Chat","d":"com.alecdorrington.iris.Chat","k":"def","x":""},
{"l":"com/alecdorrington/iris/Chat.html#assistant-f3c","e":false,"i":"","n":"assistant","t":"assistant(content: String): Chat","d":"com.alecdorrington.iris.Chat","k":"def","x":""},
{"l":"com/alecdorrington/iris/Chat.html#user-f3c","e":false,"i":"","n":"user","t":"user(content: String): Chat","d":"com.alecdorrington.iris.Chat","k":"def","x":""},
{"l":"com/alecdorrington/iris/Chat.html#withSystem-f3c","e":false,"i":"","n":"withSystem","t":"withSystem(instructions: String): Chat","d":"com.alecdorrington.iris.Chat","k":"def","x":""},
{"l":"com/alecdorrington/iris/Completion.html#","e":false,"i":"","n":"Completion","t":"Completion(text: String, stopReason: StopReason = ..., usage: Option[Usage] = ...)","d":"com.alecdorrington.iris","k":"class","x":""},
{"l":"com/alecdorrington/iris/CompletionOptions.html#","e":false,"i":"","n":"CompletionOptions","t":"CompletionOptions(model: Option[String] = ..., maxTokens: Option[Int] = ..., temperature: Option[Double] = ..., topP: Option[Double] = ..., stopSequences: List[String] = ...)","d":"com.alecdorrington.iris","k":"class","x":""},
{"l":"com/alecdorrington/iris/LlmClient$.html#","e":false,"i":"","n":"LlmClient","t":"LlmClient","d":"com.alecdorrington.iris","k":"object","x":""},
{"l":"com/alecdorrington/iris/LlmClient$.html#apply-3ac","e":false,"i":"","n":"apply","t":"apply[F[_] : MonadThrow](config: LlmConfig, backend: Backend[F]): LlmClient[F]","d":"com.alecdorrington.iris.LlmClient","k":"def","x":""},
{"l":"com/alecdorrington/iris/LlmClient$.html#fromEnv-54b","e":false,"i":"","n":"fromEnv","t":"fromEnv[F[_] : Async]: Resource[F, Option[LlmClient[F]]]","d":"com.alecdorrington.iris.LlmClient","k":"def","x":""},
{"l":"com/alecdorrington/iris/LlmClient$.html#resource-fffff3dd","e":false,"i":"","n":"resource","t":"resource[F[_] : Async](config: LlmConfig): Resource[F, LlmClient[F]]","d":"com.alecdorrington.iris.LlmClient","k":"def","x":""},
{"l":"com/alecdorrington/iris/LlmClient.html#","e":false,"i":"","n":"LlmClient","t":"LlmClient[F[_]]","d":"com.alecdorrington.iris","k":"trait","x":""},
{"l":"com/alecdorrington/iris/LlmClient.html#complete-fffffad3","e":false,"i":"","n":"complete","t":"complete(prompt: Prompt, options: CompletionOptions = ...): F[Completion]","d":"com.alecdorrington.iris.LlmClient","k":"def","x":""},
{"l":"com/alecdorrington/iris/LlmClient.html#send-f9f","e":false,"i":"","n":"send","t":"send(chat: Chat, options: CompletionOptions = ...): F[Completion]","d":"com.alecdorrington.iris.LlmClient","k":"def","x":""},
{"l":"com/alecdorrington/iris/LlmConfig$.html#","e":false,"i":"","n":"LlmConfig","t":"LlmConfig","d":"com.alecdorrington.iris","k":"object","x":""},
{"l":"com/alecdorrington/iris/LlmConfig$.html#apiKeyVariables-0","e":false,"i":"","n":"apiKeyVariables","t":"apiKeyVariables: List[String]","d":"com.alecdorrington.iris.LlmConfig","k":"val","x":""},
{"l":"com/alecdorrington/iris/LlmConfig$.html#fromEnv-0","e":false,"i":"","n":"fromEnv","t":"fromEnv: Option[LlmConfig]","d":"com.alecdorrington.iris.LlmConfig","k":"def","x":""},
{"l":"com/alecdorrington/iris/LlmConfig$.html#optionVariables-0","e":false,"i":"","n":"optionVariables","t":"optionVariables: List[String]","d":"com.alecdorrington.iris.LlmConfig","k":"val","x":""},
{"l":"com/alecdorrington/iris/LlmConfig.html#","e":false,"i":"","n":"LlmConfig","t":"LlmConfig(provider: LlmProvider, apiKey: String, model: String, maxTokens: Int, baseUrl: Option[String] = ...)","d":"com.alecdorrington.iris","k":"class","x":""},
{"l":"com/alecdorrington/iris/LlmConfig.html#origin-fffff2ca","e":false,"i":"","n":"origin","t":"origin(default: String): String","d":"com.alecdorrington.iris.LlmConfig","k":"def","x":""},
{"l":"com/alecdorrington/iris/LlmError.html#","e":false,"i":"","n":"LlmError","t":"LlmError(message: String) extends Exception","d":"com.alecdorrington.iris","k":"enum","x":""},
{"l":"com/alecdorrington/iris/LlmError$$Http.html#","e":false,"i":"","n":"Http","t":"Http(providerName: String, code: StatusCode, detail: String) extends LlmError","d":"com.alecdorrington.iris.LlmError","k":"class","x":""},
{"l":"com/alecdorrington/iris/LlmError$$Malformed.html#","e":false,"i":"","n":"Malformed","t":"Malformed(providerName: String, detail: String) extends LlmError","d":"com.alecdorrington.iris.LlmError","k":"class","x":""},
{"l":"com/alecdorrington/iris/LlmError$$Http.html#","e":false,"i":"","n":"Http","t":"Http(providerName: String, code: StatusCode, detail: String) extends LlmError","d":"com.alecdorrington.iris.LlmError","k":"class","x":""},
{"l":"com/alecdorrington/iris/LlmError$$Malformed.html#","e":false,"i":"","n":"Malformed","t":"Malformed(providerName: String, detail: String) extends LlmError","d":"com.alecdorrington.iris.LlmError","k":"class","x":""},
{"l":"com/alecdorrington/iris/LlmProvider$.html#","e":false,"i":"","n":"LlmProvider","t":"LlmProvider","d":"com.alecdorrington.iris","k":"object","x":""},
{"l":"com/alecdorrington/iris/LlmProvider$.html#parse-fffffd22","e":false,"i":"","n":"parse","t":"parse(name: String): Option[LlmProvider]","d":"com.alecdorrington.iris.LlmProvider","k":"def","x":""},
{"l":"com/alecdorrington/iris/LlmProvider.html#","e":false,"i":"","n":"LlmProvider","t":"LlmProvider(val defaultModel: String)","d":"com.alecdorrington.iris","k":"enum","x":""},
{"l":"com/alecdorrington/iris/LlmProvider.html#Anthropic-0","e":false,"i":"","n":"Anthropic","t":"Anthropic extends LlmProvider","d":"com.alecdorrington.iris.LlmProvider","k":"val","x":""},
{"l":"com/alecdorrington/iris/LlmProvider.html#OpenAi-0","e":false,"i":"","n":"OpenAi","t":"OpenAi extends LlmProvider","d":"com.alecdorrington.iris.LlmProvider","k":"val","x":""},
{"l":"com/alecdorrington/iris/LlmProvider.html#Gemini-0","e":false,"i":"","n":"Gemini","t":"Gemini extends LlmProvider","d":"com.alecdorrington.iris.LlmProvider","k":"val","x":""},
{"l":"com/alecdorrington/iris/Message.html#","e":false,"i":"","n":"Message","t":"Message(role: Role, content: String)","d":"com.alecdorrington.iris","k":"class","x":""},
{"l":"com/alecdorrington/iris/Prompt.html#","e":false,"i":"","n":"Prompt","t":"Prompt(user: String, system: Option[String] = ...)","d":"com.alecdorrington.iris","k":"class","x":""},
{"l":"com/alecdorrington/iris/Prompt.html#toChat-0","e":false,"i":"","n":"toChat","t":"toChat: Chat","d":"com.alecdorrington.iris.Prompt","k":"def","x":""},
{"l":"com/alecdorrington/iris/Role.html#","e":false,"i":"","n":"Role","t":"Role","d":"com.alecdorrington.iris","k":"enum","x":""},
{"l":"com/alecdorrington/iris/Role.html#User-0","e":false,"i":"","n":"User","t":"User extends Role","d":"com.alecdorrington.iris.Role","k":"val","x":""},
{"l":"com/alecdorrington/iris/Role.html#Assistant-0","e":false,"i":"","n":"Assistant","t":"Assistant extends Role","d":"com.alecdorrington.iris.Role","k":"val","x":""},
{"l":"com/alecdorrington/iris/StopReason.html#","e":false,"i":"","n":"StopReason","t":"StopReason","d":"com.alecdorrington.iris","k":"enum","x":""},
{"l":"com/alecdorrington/iris/StopReason$$Other.html#","e":false,"i":"","n":"Other","t":"Other(reason: String)","d":"com.alecdorrington.iris.StopReason","k":"class","x":""},
{"l":"com/alecdorrington/iris/StopReason.html#Completed-0","e":false,"i":"","n":"Completed","t":"Completed extends StopReason","d":"com.alecdorrington.iris.StopReason","k":"val","x":""},
{"l":"com/alecdorrington/iris/StopReason.html#MaxTokens-0","e":false,"i":"","n":"MaxTokens","t":"MaxTokens extends StopReason","d":"com.alecdorrington.iris.StopReason","k":"val","x":""},
{"l":"com/alecdorrington/iris/StopReason.html#StopSequence-0","e":false,"i":"","n":"StopSequence","t":"StopSequence extends StopReason","d":"com.alecdorrington.iris.StopReason","k":"val","x":""},
{"l":"com/alecdorrington/iris/StopReason$$Other.html#","e":false,"i":"","n":"Other","t":"Other(reason: String)","d":"com.alecdorrington.iris.StopReason","k":"class","x":""},
{"l":"com/alecdorrington/iris/StopReason$.html#","e":false,"i":"","n":"StopReason","t":"StopReason","d":"com.alecdorrington.iris","k":"object","x":""},
{"l":"com/alecdorrington/iris/Usage.html#","e":false,"i":"","n":"Usage","t":"Usage(inputTokens: Int, outputTokens: Int)","d":"com.alecdorrington.iris","k":"class","x":""}];